### ISSUE TITLE
Candy CSOE H7A2TE-S appliances data

### ISSUE THREAD

**Issue by rammytheone** [Andre0512/hon-test-data#48]
Device Info
```
data:
  additional_data:
    dictionaryId: 198
    options: hybrid
  appliance:
    PK: user#eu-west-1:2bff58c4-0bdf-4b91-a37c-01b426105437
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#1970-01-01T00:00:00.0Z
    applianceModelId: 625
    applianceStatus: 1
    applianceTypeId: 8
    applianceTypeName: TD
    attributes:
      acuVersion: 3.C.0
      chipset: ESP32D0WDQ5
      dictionaryId: 198
      fwLabel: sdui
      lang: it-IT
      uiVersion: 3.C.5
    brand: candy
    code: 31102187
    connectivity: wifi|ble
    defaultWarrantyYears: 2
    eepromId: 615
    eepromName: 40017712
    enrollmentDate: 1970-01-01T00:00:00.0Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 3.2.5
    id: 625
    lastUpdate: 1970-01-01T00:00:00.0Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: CSOE H7A2TE-S
    nickName: Suszarka bębnowa
    purchaseDate: 1970-01-01T00:00:00.0Z
    sections:
      chatbot: True
      demo: True
      ecoDelayStart: True
      inventory: True
      snap_and_dry: True
      snap_wash: True
    series: smartPro
    structure: heatpump
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    active: False
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          ecoDelayStart: 0
          energyLabel: 0
          functionalId: 3
          programCluster: specialCare
          programFamily: [download|guided]
          programRules:
            dryLevel:
              opt3:
                1:
                  fixedValue: 1
                  typology: fixed
            dryTime:
              dryTimeMM:
                100:
                  fixedValue: 7
                  typology: fixed
                110:
                  fixedValue: 8
                  typology: fixed
                120:
                  fixedValue: 9
                  typology: fixed
                130:
                  fixedValue: 10
                  typology: fixed
                140:
                  fixedValue: 11
                  typology: fixed
                150:
                  fixedValue: 12
                  typology: fixed
                160:
                  fixedValue: 13
                  typology: fixed
                170:
                  fixedValue: 14
                  typology: fixed
                180:
                  fixedValue: 15
                  typology: fixed
                190:
                  fixedValue: 16
                  typology: fixed
                200:
                  fixedValue: 17
                  typology: fixed
                210:
                  fixedValue: 18
                  typology: fixed
                220:
                  fixedValue: 19
                  typology: fixed
                30:
                  fixedValue: 1
                  typology: fixed
                45:
                  fixedValue: 2
                  typology: fixed
                59:
                  fixedValue: 3
                  typology: fixed
                70:
                  fixedValue: 4
                  typology: fixed
                80:
                  fixedValue: 5
                  typology: fixed
                90:
                  fixedValue: 6
                  typology: fixed
            opt3:
              dryLevel:
                2|3|4:
                  fixedValue: 0
                  typology: fixed
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadD: 2
        applianceOptions:
          opt1: anticrease
          opt2: dryingManager
          opt3: bestIroning
          opt4: hybrid
        applianceType: TD
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: lastProgram
          prStr: Bielizna
        commandName: startProgram
        device:
          appVersion: 2.12.9
          deviceModel: YAL
          mobileId: db208b042d268cbd
          mobileOs: android
          osVersion: 29
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          anticrease: 0
          autoDetergentStatus: 0
          autoSoftenerStatus: 0
          checkUpStatus: 0
          delayTime: 0
          dryLevel: 2
          dryTime: 0
          dryingManager: 1
          hybrid: 0
          onOffStatus: 1
          prCode: 6
          prPosition: 7
        programName: PROGRAMS.TD.IOT_DRY_LINGERIE
        timestamp: 1970-01-01T00:00:00.0Z
        transactionId: xx-xx-xx-xx-xx-xx_1970-01-01T00:00:00.0Z
      timestampAccepted: 1970-01-01T00:00:00.0Z
      timestampExecuted: 1970-01-01T00:00:00.0Z
    lastConnEvent:
      category: DISCONNECTED
      instantTime: 1970-01-01T00:00:00.0Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1728530211893
    parameters:
      anticrease: 1
      bestIroning: 0
      checkUpStatus: 0
      delayTime: 0
      doorStatus: 0
      dryCotton120: 4
      dryCotton180: 0
      dryCotton60: 120
      dryCottonBone: 65
      dryCottonHang: 77
      dryCottonIron: 0
      dryCottonMax: 0
      dryCottonStore: 102
      dryFilterStatus: 1
      dryLevel: 3
      dryLevelMgmt: 2
      drySynth120: 0
      drySynth180: 0
      drySynth60: 0
      drySynthBone: 26
      drySynthHang: 55
      drySynthIron: 0
      drySynthMax: 0
      drySynthStore: 32
      dryTime: 0
      dryingManager: 1
      errors: 00
      hybrid: 0
      machMode: 7
      opt5: 0
      opt6: 0
      opt7: 0
      opt8: 0
      prCode: 0
      prPhase: 0
      prPosition: 5
      program1: 0
      program10: 14
      program10t: 46
      program11: 36
      program11t: 31
      program12: 30
      program12t: 21
      program13: 35
      program13t: 13
      program14: 0
      program14t: 0
      program15: 44
      program15t: 79
      program16: 8
      program16t: 94
      program17: 4
      program17t: 30
      program18: 0
      program18t: 0
      program19: 0
      program19t: 0
      program1t: 0
      program2: 6
      program20: 0
      program20t: 0
      program21: 0
      program21t: 0
      program2t: 196
      program3: 19
      program3t: 36
      program4: 45
      program4t: 176
      program5: 95
      program5t: 112
      program6: 35
      program6t: 106
      program7: 78
      program7t: 70
      program8: 4
      program8t: 71
      program9: 28
      program9t: 59
      remainingTimeMM: 0
      remoteCtrValid: 0
      tumblingStatus: 0
      waterTankStatus: 0
    pause: False
    programName: No Program
    resultCode: 0
  extra_command_data:
    startProgram:
      dryLevel:
        2: 150
      remainingTimeMM:
        category: command
        incrementValue: 1
        mandatory: 0
        typology: range 
  pauseProgram:
    parameters:
      pause: 1
  resumeProgram:
    parameters:
      pause: 0
  settings:
    custom:
      category: setParameters
    parameters:
      resW: 1
      tumblingStatus: 0
  startProgram:
    ancillaryParameters:
      energyLabel: 5
      functionalId: 26
      programFamily: [dashboard|auto]
      programRules: {'dryLevel': {'opt3': {'1': {'typology': 'fixed', 'fixedValue': '1'}}}, 'opt3': {'dryLevel': {'2|3|4': {'typology': 'fixed', 'fixedValue': '0'}}}, 'dryTime': {'dryTimeMM': {'30': {'typology': 'fixed', 'fixedValue': '1'}, '45': {'typology': 'fixed', 'fixedValue': '2'}, '59': {'typology': 'fixed', 'fixedValue': '3'}, '70': {'typology': 'fixed', 'fixedValue': '4'}, '80': {'typology': 'fixed', 'fixedValue': '5'}, '90': {'typology': 'fixed', 'fixedValue': '6'}, '100': {'typology': 'fixed', 'fixedValue': '7'}, '110': {'typology': 'fixed', 'fixedValue': '8'}, '120': {'typology': 'fixed', 'fixedValue': '9'}, '130': {'typology': 'fixed', 'fixedValue': '10'}, '140': {'typology': 'fixed', 'fixedValue': '11'}, '150': {'typology': 'fixed', 'fixedValue': '12'}, '160': {'typology': 'fixed', 'fixedValue': '13'}, '170': {'typology': 'fixed', 'fixedValue': '14'}, '180': {'typology': 'fixed', 'fixedValue': '15'}, '190': {'typology': 'fixed', 'fixedValue': '16'}, '200': {'typology': 'fixed', 'fixedValue': '17'}, '210': {'typology': 'fixed', 'fixedValue': '18'}, '220': {'typology': 'fixed', 'fixedValue': '19'}}}}
      remoteActionable: 1
      remoteVisible: 1
      suggestedLoadD: 7
    custom:
      program: eco
    parameters:
      anticrease: 0
      bestIroning: 0
      checkUpStatus: 0
      delayTime: 0
      dryLevel: 2
      dryingManager: 1
      hybrid: 0
      onOffStatus: 1
      prCode: 6
      prPosition: 7
      prStr: 0
  statistics:
    drumCleaning:
      count: 0
      percentage: 0
      remaining: 100
      tot: 100
    filterCleaning:
      count: 0
      percentage: 0
      remaining: 15
      tot: 15
    lastCheckup: 1970-01-01T00:00:00.0Z
    loadingPercentage:
    mostUsedPrograms:
      - count: 81
        prCode: 0
        prPosition: 5
        programName: PROGRAMS.TD.DARKS_AND_COLOURED
        programType: D
      - count: 43
        prCode: 0
        prPosition: 15
        programName: PROGRAMS.TD.SMALL_LOAD
        programType: D
      - count: 41
        prCode: 6
        prPosition: 7
        programName: PROGRAMS.TD.IOT_DRY_LINGERIE
        programType: D
      - count: 38
        prCode: 0
        prPosition: 4
        programName: PROGRAMS.TD.JEANS
        programType: D
      - count: 35
        prCode: 0
        prPosition: 7
        programName: PROGRAMS.TD.SHIRTS
        programType: D
    programsCounter: 480
    resultCode: 0
    sprayArmsCleaning: 0
    temperatureUsage:
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
  startProgram:
    anticrease:
      max: 1
      min: 0
      step: 1
    bestIroning:
      max: 1
      min: 0
      step: 1
    delayTime:
      max: 1410
      min: 0
      step: 30
    dryLevel:
      max: 4
      min: 1
      step: 1
    dryTime:
      max: 19
      min: 4
      step: 1
    dryTimeMM:
      max: 220
      min: 70
      step: 10
    energyLabel:
      max: 5
      min: 1
      step: 1
    program:
      - daily_45_min
      - daily_perfect_59_min
      - darks_and_coloured
      - eco
      - iot_checkup
      - iot_dry_anti_mites
      - iot_dry_baby
      - iot_dry_backpacks
      - iot_dry_bathrobe
      - iot_dry_bed_linen
      - iot_dry_bed_quilt
      - iot_dry_cotton
      - iot_dry_cuddly_toys
      - iot_dry_curtains
      - iot_dry_dehumidifier
      - iot_dry_delicate_tablecloths
      - iot_dry_delicates
      - iot_dry_denim_jeans
      - iot_dry_down_jacket
      - iot_dry_duvet
      - iot_dry_easy_iron_cotton
      - iot_dry_easy_iron_synthetics
      - iot_dry_gym_fit
      - iot_dry_lingerie
      - iot_dry_mixed
      - iot_dry_playsuits
      - iot_dry_rapid_30
      - iot_dry_rapid_59
      - iot_dry_regenerates_waterproof
      - iot_dry_shirts
      - iot_dry_small_load
      - iot_dry_swimsuits_and_bikinis
      - iot_dry_synthetics
      - iot_dry_tablecloths
      - iot_dry_technical_fabrics
      - iot_dry_warm_embrace
      - iot_dry_wool
      - jeans
      - mix_and_dry
      - rapid_30
      - refresh
      - relax_creases
      - saving_30_min
      - shirts
      - small_load
      - sport_plus
      - synthetics
      - trainers
      - whites
      - woolmark
      - xxl_load
    programCluster:
      - care
      - home
      - hygiene
      - care_home_hygiene
    programFamily:
      - guided
      - wmsync
      - voice
      - care
      - guided_wmsync_voice_care
rules:
  startProgram:
    dryLevel:
      2:
        opt3: 0
      3:
        opt3: 0
      4:
        opt3: 0
    dryTimeMM:
      100:
        dryTime: 7
      110:
        dryTime: 8
      120:
        dryTime: 9
      130:
        dryTime: 10
      140:
        dryTime: 11
      150:
        dryTime: 12
      160:
        dryTime: 13
      170:
        dryTime: 14
      180:
        dryTime: 15
      190:
        dryTime: 16
      200:
        dryTime: 17
      210:
        dryTime: 18
      220:
        dryTime: 19
      30:
        dryTime: 1
      45:
        dryTime: 2
      59:
        dryTime: 3
      70:
        dryTime: 4
      80:
        dryTime: 5
      90:
        dryTime: 6

```

[td_625.zip](https://github.com/user-attachments/files/17324023/td_625.zip)
